// Milky Way glow layer - samples the baked all-sky texture (data/galaxy_glow.png,
// generated by scripts/build-galaxy-glow.js from the real star catalog) and
// draws it as an ADDITIVE fullsky pass BEHIND the star points.
//
// Geometry: an inward-facing unit cube around the camera, transformed exactly
// like the star points (direction * large radius, rotation-only camera), so
// the glow is locked to the celestial sphere with zero extra plumbing. The
// per-vertex cube-corner direction is interpolated (perspective-correct
// interpolation lands on the ray/cube intersection) and normalized per
// fragment, which yields the exact view direction for every pixel.
//
// ── THE EQUIRECT MAPPING CONTRACT ──
// Direction (equatorial J2000, x = vernal equinox, z = north celestial pole)
// to texture uv. This formula MUST stay byte-identical in three places (it is
// the only alignment contract between the baked texture and the live stars):
//   1. scripts/build-galaxy-glow.js (accumulation),
//   2. THIS shader + the embedded fallback copy in src/renderer/stars.rs,
//   3. src/renderer/stars.rs::dir_to_equirect_uv (pure fn + unit tests).
//
//   u = atan2(dir.y, dir.x) / (2*pi) + 0.5     (RA;  wraps at the u=0/1 seam)
//   v = acos(clamp(dir.z, -1, 1)) / pi         (Dec; 0 = north celestial pole)
//
// The sampler wraps in u (AddressMode::Repeat) so the RA seam is invisible,
// and clamps in v. The texture is Rgba8Unorm (NOT sRGB): its texels feed the
// framebuffer exactly like star vertex colors do, so the bake's tone map is
// WYSIWYG relative to star brightness.

// Must match the Rust-side CameraUniforms struct exactly (672 bytes, v0.639).
struct CameraUniforms {
    view_proj: mat4x4<f32>,
    view_pos: vec4<f32>,
    // Point lights (unused by the glow, but must match the buffer layout)
    light0: vec4<f32>, light1: vec4<f32>, light2: vec4<f32>, light3: vec4<f32>,
    light4: vec4<f32>, light5: vec4<f32>, light6: vec4<f32>, light7: vec4<f32>,
    light0_color: vec4<f32>, light1_color: vec4<f32>, light2_color: vec4<f32>, light3_color: vec4<f32>,
    light4_color: vec4<f32>, light5_color: vec4<f32>, light6_color: vec4<f32>, light7_color: vec4<f32>,
    light0_spot: vec4<f32>, light1_spot: vec4<f32>, light2_spot: vec4<f32>, light3_spot: vec4<f32>,
    light4_spot: vec4<f32>, light5_spot: vec4<f32>, light6_spot: vec4<f32>, light7_spot: vec4<f32>,
    light0_cone_inner: vec4<f32>, light1_cone_inner: vec4<f32>, light2_cone_inner: vec4<f32>, light3_cone_inner: vec4<f32>,
    light4_cone_inner: vec4<f32>, light5_cone_inner: vec4<f32>, light6_cone_inner: vec4<f32>, light7_cone_inner: vec4<f32>,
    light_count: vec4<f32>,
    sun_direction: vec4<f32>,
    sun_color: vec4<f32>,
    fill_direction: vec4<f32>,
    fill_color: vec4<f32>,
};
@group(0) @binding(0)
var<uniform> camera: CameraUniforms;

@group(1) @binding(0)
var glow_tex: texture_2d<f32>;
@group(1) @binding(1)
var glow_samp: sampler;
// x = intensity (Settings > Graphics "Milky Way glow" slider, 0..2); yzw pad.
@group(1) @binding(2)
var<uniform> glow_params: vec4<f32>;

struct GlowInput {
    @location(0) direction: vec3<f32>,
};

struct GlowOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) dir: vec3<f32>,
};

@vertex
fn vs_main(input: GlowInput) -> GlowOutput {
    var out: GlowOutput;
    // Same placement as the star points: far away, rotation-only camera.
    let world_pos = input.direction * 5000.0;
    out.clip_position = camera.view_proj * vec4<f32>(world_pos, 1.0);
    out.dir = input.direction;
    return out;
}

@fragment
fn fs_main(input: GlowOutput) -> @location(0) vec4<f32> {
    let d = normalize(input.dir);
    // THE mapping contract (see header). 6.2831853 = 2*pi, 3.14159265 = pi.
    let u = atan2(d.y, d.x) / 6.28318530717958647692 + 0.5;
    let v = acos(clamp(d.z, -1.0, 1.0)) / 3.14159265358979323846;
    let c = textureSample(glow_tex, glow_samp, vec2<f32>(u, v)).rgb;
    // Additive blend (ONE, ONE): output = glow + whatever is behind (black).
    return vec4<f32>(c * glow_params.x, 1.0);
}
