//! Library: an in-app reader for the project's reference docs (the Humanity
//! Accord and its companions), loaded data-driven from `data/library/` (a
//! manifest + markdown files, generated by `scripts/build-library.js`). A
//! top-level tab (operator 2026-06-06: "a top level Library button that contains
//! all the docs sorted into nested categories kinda like the inventory"): a
//! nested category tree on the left, the selected document on the right. The doc
//! pane renders markdown via the shared `widgets::markdown` reader, the same one
//! the Humanity Accord viewer uses.

use egui::{Align, Frame, Layout, RichText, ScrollArea, Vec2};
use crate::gui::GuiState;
use crate::gui::theme::Theme;
use crate::gui::widgets::markdown;

/// Page-local selection: (category index, doc index). Defaults to the first doc.
fn selected<R>(f: impl FnOnce(&mut (usize, usize)) -> R) -> R {
    use std::cell::RefCell;
    thread_local! {
        static SEL: RefCell<(usize, usize)> = RefCell::new((0, 0));
    }
    SEL.with(|s| f(&mut s.borrow_mut()))
}

pub fn draw(ctx: &egui::Context, theme: &Theme, state: &mut GuiState) {
    egui::CentralPanel::default()
        .frame(Frame::none().fill(theme.bg_panel()).inner_margin(16.0))
        .show(ctx, |ui| {
            ui.label(RichText::new("Library").size(theme.font_size_title).color(theme.text_primary()));
            ui.label(
                RichText::new("The Humanity Accord and the reference it rests on. Read it, adopt it for your own community, or hold us to it.")
                    .size(theme.font_size_small)
                    .color(theme.text_muted()),
            );
            ui.separator();

            if state.library.is_empty() {
                ui.label(
                    RichText::new("No documents loaded. Run scripts/build-library.js to populate data/library/.")
                        .color(theme.text_muted()),
                );
                return;
            }

            let rail_w = 240.0;
            let content_w = (ui.available_width() - rail_w - 24.0).max(280.0);
            let body_h = ui.available_height();

            ui.horizontal_top(|ui| {
                // Left rail: nested category -> doc tree.
                ui.allocate_ui_with_layout(Vec2::new(rail_w, body_h), Layout::top_down(Align::Min), |ui| {
                    ScrollArea::vertical().id_salt("library_rail").auto_shrink([false, false]).show(ui, |ui| {
                        selected(|sel| {
                            if sel.0 >= state.library.len() {
                                *sel = (0, 0);
                            }
                            for (ci, cat) in state.library.iter().enumerate() {
                                egui::CollapsingHeader::new(
                                    RichText::new(cat.name.as_str()).strong().color(theme.accent()),
                                )
                                .id_salt(("lib_cat", ci))
                                .default_open(true)
                                .show(ui, |ui| {
                                    for (di, doc) in cat.docs.iter().enumerate() {
                                        let is_sel = *sel == (ci, di);
                                        let color = if is_sel { theme.accent() } else { theme.text_primary() };
                                        if ui
                                            .selectable_label(is_sel, RichText::new(doc.title.as_str()).color(color))
                                            .clicked()
                                        {
                                            *sel = (ci, di);
                                        }
                                    }
                                });
                            }
                        });
                    });
                });

                ui.separator();

                // Right: the selected document.
                ui.allocate_ui_with_layout(Vec2::new(content_w, body_h), Layout::top_down(Align::Min), |ui| {
                    selected(|sel| {
                        if let Some(doc) = state.library.get(sel.0).and_then(|c| c.docs.get(sel.1)) {
                            ScrollArea::vertical()
                                .id_salt("library_doc")
                                .auto_shrink([false, false])
                                .show(ui, |ui| {
                                    markdown::render_markdown(ui, theme, doc.body.as_str());
                                });
                        }
                    });
                });
            });
        });
}
