#!/usr/bin/env node
// Builds the in-app Library's runtime data. Reads the taxonomy from
// data/library/catalog.json, copies each listed source doc into data/library/,
// and generates data/library/index.json (the manifest both clients read).
// Re-run after editing the catalog or any source doc.
//
// Data-driven (infinite-of-X): the taxonomy is DATA, not code. Before v0.1305
// the full list of 16 categories and 80 documents lived in this file as a
// `const CATEGORIES = [...]` literal, which is exactly the shape
// docs/design/infinite-of-x.md forbids: a list of domain objects hardcoded in a
// script. Adding a document is now a row in catalog.json and nothing else.
//
// Why two files: catalog.json is the CURATED SOURCE (it points at repo paths
// under docs/, which are not distributed), index.json is the GENERATED RUNTIME
// manifest (it points at the flat copies in data/library/, which are shipped
// next to the exe). Native reads index.json via load_library() in
// src/gui/mod.rs; web reads the same file in web/pages/library-app.js.

const fs = require('fs');
const path = require('path');

const LIB = 'data/library';
const CATALOG = path.join(LIB, 'catalog.json');
const TAGS = path.join(LIB, 'tags.json');

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    console.error('library: could not read ' + file + ': ' + err.message);
    process.exit(1);
  }
}

const catalog = readJson(CATALOG);
const tagsDoc = readJson(TAGS);

// Flatten the tag registry into a lookup, and refuse to build on an unknown tag.
// Without this check a typo in catalog.json ships a chip with no label and a
// filter nothing matches, which is invisible until a user notices.
const knownTags = new Map();
for (const group of tagsDoc.groups || []) {
  for (const t of group.tags || []) knownTags.set(t.id, t.label || t.id);
}

const categories = catalog.categories || [];
const badTags = [];
for (const cat of categories) {
  for (const d of cat.docs || []) {
    for (const t of d.tags || []) {
      if (!knownTags.has(t)) badTags.push(t + ' (on "' + d.title + '")');
    }
  }
}
if (badTags.length) {
  console.error('library: catalog.json uses tags that tags.json does not define:');
  for (const b of badTags) console.error('  - ' + b);
  console.error('Add them to ' + TAGS + ' or fix the typo.');
  process.exit(1);
}

fs.mkdirSync(LIB, { recursive: true });

const manifest = {
  _comment:
    'In-app Library manifest. GENERATED by scripts/build-library.js from ' +
    'data/library/catalog.json - edit the catalog, not this file. Nested ' +
    'categories of reference docs; the app reads each doc from ' +
    'data/library/<file>. `tags` are defined in data/library/tags.json.',
  tags: tagsDoc.groups || [],
  sections: catalog._sections || [],
  categories: [],
};

let copied = 0;
const missing = [];
const used = new Set();
const rewrites = [];  // {file, src} for the link-rewrite pass

for (const cat of categories) {
  const entry = { name: cat.name, docs: [] };
  // The section a category belongs to. Three tiers (section > category >
  // document) rather than two, because a flat 17-category rail was already a
  // long scroll and the syllabus commits us to far more.
  if (cat.section) entry.section = cat.section;
  // The Accord subset is flagged so /accord can render exactly those
  // categories from THIS manifest instead of a separate relay endpoint.
  if (cat.accord) entry.accord = true;

  for (const d of cat.docs || []) {
    if (!fs.existsSync(d.src)) { missing.push(d.src); continue; }

    // Collision-safe target name: basename first; if taken (README.md exists in
    // four source folders), fall back to the full path slug. The check is
    // CASE-INSENSITIVE: ONBOARDING.md (docs/user) and onboarding.md (docs/ai)
    // are different keys to a Set but the SAME file on Windows, so one silently
    // overwrote the other while the manifest listed both; the case-sensitive
    // live server then 404ed the loser (found by the 2026-07-31 doc-truth sweep).
    let file = path.basename(d.src);
    if (used.has(file.toLowerCase())) {
      file = d.src.replace(/^docs\//, '').replace(/[\/\\]/g, '-');
    }
    used.add(file.toLowerCase());

    // Rewrite the doc's own cross-references as it is copied. Sources live in
    // a folder tree (docs/user/, docs/admin/, ...) and link to each other
    // relatively, but the Library flattens everything into one directory, so
    // every "../admin/SELF-HOSTING.md" style link was dead in the shipped app
    // and on the website. 21 of them across 6 documents, including the
    // getting-started hand-off to self-hosting.
    //
    // A link whose target IS in the catalogue becomes the Library's own deep
    // link (/library#<slug>, the grammar web/pages/library-app.js already
    // implements). A link to something NOT shipped becomes a GitHub URL, which
    // at least resolves. Both are computed in pass 2 below, once every
    // catalogue entry's flat filename is known.
    fs.copyFileSync(d.src, path.join(LIB, file));
    rewrites.push({ file, src: d.src });
    const doc = { title: d.title, file };
    if (d.tags && d.tags.length) doc.tags = d.tags;
    entry.docs.push(doc);
    copied++;
  }

  if (entry.docs.length) manifest.categories.push(entry);
}

// ── Pass 2: rewrite cross-document links now that every flat name is known ──
// srcPath -> flat shipped filename, for everything in the catalogue.
const shipped = new Map();
const toPosix = p => p.split(path.sep).join('/').replace(/\\/g, '/');
for (const r of rewrites) shipped.set(path.posix.normalize(toPosix(r.src)), r.file);

const GITHUB = 'https://github.com/Shaostoul/Humanity/blob/main/';
const slugOf = f => f.replace(/\.md$/i, '').replace(/_/g, '-').toLowerCase();

let linksRewritten = 0, linksToGithub = 0;
for (const r of rewrites) {
  const p = path.join(LIB, r.file);
  const before = fs.readFileSync(p, 'utf8');
  const srcDir = path.posix.dirname(toPosix(r.src));

  const after = before.replace(/\]\(([^)\s]+\.md)(#[^)]*)?\)/g, (whole, target, frag) => {
    if (/^https?:/i.test(target)) return whole;
    const abs = path.posix.normalize(path.posix.join(srcDir, target));
    const flat = shipped.get(abs);
    if (flat) { linksRewritten++; return '](/library#' + slugOf(flat) + ')'; }
    // Not shipped in the Library: point at the repo so it at least resolves.
    linksToGithub++;
    return '](' + GITHUB + abs + (frag || '') + ')';
  });

  if (after !== before) fs.writeFileSync(p, after);
}
console.log('library: rewrote ' + linksRewritten + ' cross-doc links to /library#slug, ' + linksToGithub + ' to GitHub');
// ── Pass 3: the search index ──
// The Library had no document search at all: both clients' only search box
// searched the Dictionary's glossary terms. At 83 documents you can browse a
// 17-category rail; at 500 you cannot, and browsing is the only affordance
// there was.
//
// The index carries full text so results can show a real snippet rather than
// just a title, which costs about 800 KB uncompressed. That is why the web
// client LAZY-LOADS it on the first keystroke rather than on page load: nobody
// pays for search until they search. Native needs none of this (it already
// holds every document body in memory) but reads the same headings so the two
// clients rank and display alike.
const searchDocs = [];
for (const cat of manifest.categories) {
  for (const d of cat.docs) {
    const text = fs.readFileSync(path.join(LIB, d.file), 'utf8');
    const headings = [];
    for (const m of text.matchAll(/^#{1,4}\s+(.+)$/gm)) {
      headings.push(m[1].replace(/[*`]/g, '').trim());
    }
    searchDocs.push({
      slug: slugOf(d.file),
      title: d.title,
      category: cat.name,
      tags: d.tags || [],
      headings,
      // Whitespace collapsed; markup left in place because stripping it would
      // change offsets and the snippet is rendered as plain text anyway.
      text: text.replace(/\s+/g, ' ').trim(),
    });
  }
}
fs.writeFileSync(
  path.join(LIB, 'search-index.json'),
  JSON.stringify({
    _comment:
      'GENERATED by scripts/build-library.js. Full-text search index for the ' +
      'Library. Lazy-loaded by web/pages/library-app.js on the first search ' +
      'keystroke, never on page load. Native searches its in-memory bodies ' +
      'instead and does not read this.',
    docs: searchDocs,
  }) + '\n'
);
const idxKb = Math.round(fs.statSync(path.join(LIB, 'search-index.json')).size / 1024);
console.log('library: search index ' + searchDocs.length + ' docs, ' + idxKb + ' KB (lazy-loaded)');

fs.writeFileSync(path.join(LIB, 'index.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(
  'library: copied ' + copied + ' docs into ' + LIB + '/ across ' +
  manifest.categories.length + ' categories, ' + knownTags.size + ' tags defined'
);
if (missing.length) console.log('  (skipped missing: ' + missing.join(', ') + ')');
