#!/usr/bin/env node
// Builds the in-app Library's data: copies a curated set of reference docs into
// data/library/ and generates data/library/index.json (the nested-category
// manifest the Library page reads). Re-run after editing or adding source docs.
//
// Data-driven (infinite-of-X): the app loads the manifest + the .md files at
// startup; adding a doc means dropping a file in data/library/ and adding a line
// here (or directly to index.json), never touching Rust. Source docs live in
// docs/; this ships a stable, curated user-facing copy in data/ (which is
// distributed next to the exe, where docs/ is not).

const fs = require('fs');
const path = require('path');

const LIB = 'data/library';

// Curated, nested categories. Sources are repo paths; only ones that exist are
// included (missing ones are reported, not fatal).
const CATEGORIES = [
  { name: 'Credits', docs: [
    { title: 'Credits and Thanks', src: 'CREDITS.md' },
  ]},
  { name: 'The Accord', docs: [
    { title: 'The Humanity Accord', src: 'docs/accord/humanity_accord.md' },
    { title: 'Absolute Prohibitions', src: 'docs/accord/absolute_prohibitions.md' },
  ]},
  { name: 'Your Rights and Consent', docs: [
    { title: 'Rights and Responsibilities', src: 'docs/accord/rights_and_responsibilities.md' },
    { title: 'Consent and Control', src: 'docs/accord/consent_and_control.md' },
    { title: 'Communication and Association', src: 'docs/accord/communication_and_association.md' },
  ]},
  { name: 'How We Decide', docs: [
    { title: 'Ethical Principles', src: 'docs/accord/ethical_principles.md' },
    { title: 'Conflict Resolution', src: 'docs/accord/conflict_resolution.md' },
    { title: 'Transparency Guarantees', src: 'docs/accord/transparency_guarantees.md' },
    { title: 'When Legitimacy Fails', src: 'docs/accord/failure_of_legitimacy.md' },
  ]},
  { name: 'Safety and Care', docs: [
    { title: 'Human Needs', src: 'docs/accord/human_needs.md' },
    { title: 'Safety and Responsibility', src: 'docs/accord/safety_and_responsibility.md' },
    { title: 'Harm and Responsibility', src: 'docs/accord/harm_and_responsibility.md' },
    { title: 'Irreversible Actions', src: 'docs/accord/irreversible_actions.md' },
    { title: 'User Safety Overview', src: 'docs/accord/user_safety_overview.md' },
  ]},
  { name: 'Reference', docs: [
    { title: 'Glossary', src: 'docs/accord/glossary.md' },
    { title: 'Scope and Boundaries', src: 'docs/accord/scope_boundaries.md' },
    { title: 'Knowledge Sources', src: 'docs/accord/knowledge_sources.md' },
  ]},
];

fs.mkdirSync(LIB, { recursive: true });
const manifest = {
  _comment: 'In-app Library manifest. Generated by scripts/build-library.js. Nested categories of reference docs; the app reads each doc from data/library/<file>. Edit the script or this file to curate.',
  categories: [],
};
let copied = 0;
const missing = [];
for (const cat of CATEGORIES) {
  const entry = { name: cat.name, docs: [] };
  for (const d of cat.docs) {
    if (!fs.existsSync(d.src)) { missing.push(d.src); continue; }
    const file = path.basename(d.src);
    fs.copyFileSync(d.src, path.join(LIB, file));
    entry.docs.push({ title: d.title, file });
    copied++;
  }
  if (entry.docs.length) manifest.categories.push(entry);
}
fs.writeFileSync(path.join(LIB, 'index.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`library: copied ${copied} docs into ${LIB}/ across ${manifest.categories.length} categories`);
if (missing.length) console.log('  (skipped missing: ' + missing.join(', ') + ')');
