#!/usr/bin/env node
// Builds the in-app Library's runtime data. Reads the taxonomy from
// data/library/catalog.json, copies each listed source doc into data/library/,
// and generates data/library/index.json (the manifest both clients read).
// Re-run after editing the catalog or any source doc.
//
// Data-driven (infinite-of-X): the taxonomy is DATA, not code. Before v0.1305
// the full list of 16 categories and 80 documents lived in this file as a
// `const CATEGORIES = [...]` literal, which is exactly the shape
// docs/design/infinite-of-x.md forbids: a list of domain objects hardcoded in a
// script. Adding a document is now a row in catalog.json and nothing else.
//
// Why two files: catalog.json is the CURATED SOURCE (it points at repo paths
// under docs/, which are not distributed), index.json is the GENERATED RUNTIME
// manifest (it points at the flat copies in data/library/, which are shipped
// next to the exe). Native reads index.json via load_library() in
// src/gui/mod.rs; web reads the same file in web/pages/library-app.js.

const fs = require('fs');
const path = require('path');

const LIB = 'data/library';
const CATALOG = path.join(LIB, 'catalog.json');
const TAGS = path.join(LIB, 'tags.json');

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    console.error('library: could not read ' + file + ': ' + err.message);
    process.exit(1);
  }
}

const catalog = readJson(CATALOG);
const tagsDoc = readJson(TAGS);

// Flatten the tag registry into a lookup, and refuse to build on an unknown tag.
// Without this check a typo in catalog.json ships a chip with no label and a
// filter nothing matches, which is invisible until a user notices.
const knownTags = new Map();
for (const group of tagsDoc.groups || []) {
  for (const t of group.tags || []) knownTags.set(t.id, t.label || t.id);
}

const categories = catalog.categories || [];
const badTags = [];
for (const cat of categories) {
  for (const d of cat.docs || []) {
    for (const t of d.tags || []) {
      if (!knownTags.has(t)) badTags.push(t + ' (on "' + d.title + '")');
    }
  }
}
if (badTags.length) {
  console.error('library: catalog.json uses tags that tags.json does not define:');
  for (const b of badTags) console.error('  - ' + b);
  console.error('Add them to ' + TAGS + ' or fix the typo.');
  process.exit(1);
}

fs.mkdirSync(LIB, { recursive: true });

const manifest = {
  _comment:
    'In-app Library manifest. GENERATED by scripts/build-library.js from ' +
    'data/library/catalog.json - edit the catalog, not this file. Nested ' +
    'categories of reference docs; the app reads each doc from ' +
    'data/library/<file>. `tags` are defined in data/library/tags.json.',
  tags: tagsDoc.groups || [],
  categories: [],
};

let copied = 0;
const missing = [];
const used = new Set();

for (const cat of categories) {
  const entry = { name: cat.name, docs: [] };
  // The Accord subset is flagged so /accord can render exactly those
  // categories from THIS manifest instead of a separate relay endpoint.
  if (cat.accord) entry.accord = true;

  for (const d of cat.docs || []) {
    if (!fs.existsSync(d.src)) { missing.push(d.src); continue; }

    // Collision-safe target name: basename first; if taken (README.md exists in
    // four source folders), fall back to the full path slug. The check is
    // CASE-INSENSITIVE: ONBOARDING.md (docs/user) and onboarding.md (docs/ai)
    // are different keys to a Set but the SAME file on Windows, so one silently
    // overwrote the other while the manifest listed both; the case-sensitive
    // live server then 404ed the loser (found by the 2026-07-31 doc-truth sweep).
    let file = path.basename(d.src);
    if (used.has(file.toLowerCase())) {
      file = d.src.replace(/^docs\//, '').replace(/[\/\\]/g, '-');
    }
    used.add(file.toLowerCase());

    fs.copyFileSync(d.src, path.join(LIB, file));
    const doc = { title: d.title, file };
    if (d.tags && d.tags.length) doc.tags = d.tags;
    entry.docs.push(doc);
    copied++;
  }

  if (entry.docs.length) manifest.categories.push(entry);
}

fs.writeFileSync(path.join(LIB, 'index.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(
  'library: copied ' + copied + ' docs into ' + LIB + '/ across ' +
  manifest.categories.length + ' categories, ' + knownTags.size + ' tags defined'
);
if (missing.length) console.log('  (skipped missing: ' + missing.join(', ') + ')');
