//! Vehicle & mech system — entering/exiting vehicles, mech torso twist,
//! jump jets, heat management, and vehicle movement control.
//!
//! Vehicle definitions loaded from `data/vehicles.csv`.
//! Ship-specific logic in `ships.rs`, propulsion physics in `propulsion.rs`.

pub mod ships;
pub mod propulsion;

use std::collections::HashMap;

use glam::Vec3;

use crate::ecs::components::{Controllable, Transform, Velocity, VehicleSeat};
use crate::ecs::systems::System;
use crate::hot_reload::data_store::DataStore;

/// Heat dissipation rate per second (fraction of max heat).
const HEAT_DISSIPATION_RATE: f32 = 0.05;
/// Heat threshold above which weapons are disabled (fraction, 0-1).
const OVERHEAT_THRESHOLD: f32 = 0.9;
/// Heat threshold below which weapons re-enable after overheat.
const COOLDOWN_THRESHOLD: f32 = 0.5;
/// Jump jet fuel consumption rate per second while jetting.
const JUMP_JET_FUEL_RATE: f32 = 0.15;
/// Upward impulse applied per second while jump jets fire (m/s per second).
const JUMP_JET_IMPULSE: f32 = 12.0;
/// Maximum torso twist angle in radians (~90 degrees each way).
const MAX_TORSO_YAW: f32 = std::f32::consts::FRAC_PI_2;
/// Distance from vehicle center to place player on exit (meters).
const EXIT_OFFSET: f32 = 3.0;

// ── Commands passed via DataStore ───────────────────────────────────────

/// Command to enter a vehicle. Place in DataStore under key "enter_vehicle".
#[derive(Debug, Clone)]
pub struct EnterVehicleCommand {
    /// The player entity requesting entry (as entity bits).
    pub player_entity: u64,
    /// The vehicle entity to enter (as entity bits).
    pub vehicle_entity: u64,
    /// Player's public key for seat assignment.
    pub player_key: String,
}

/// Command to exit the current vehicle. Place in DataStore under key "exit_vehicle".
#[derive(Debug, Clone)]
pub struct ExitVehicleCommand {
    /// The player entity requesting exit (as entity bits).
    pub player_entity: u64,
}

/// Mech-specific per-entity state: torso rotation, heat, jump jets.
#[derive(Debug, Clone)]
pub struct MechState {
    /// Independent torso yaw relative to legs (radians, clamped to +/- MAX_TORSO_YAW).
    pub torso_yaw: f32,
    /// Current heat level (0.0 = cool, 1.0 = max heat).
    pub heat: f32,
    /// Jump jet fuel remaining (0.0 = empty, 1.0 = full).
    pub jump_jet_fuel: f32,
    /// Whether the mech is currently overheated (weapons disabled).
    pub overheated: bool,
}

impl Default for MechState {
    fn default() -> Self {
        Self {
            torso_yaw: 0.0,
            heat: 0.0,
            jump_jet_fuel: 1.0,
            overheated: false,
        }
    }
}

/// Mech input commands read from DataStore each tick under key "mech_input".
#[derive(Debug, Clone, Default)]
pub struct MechInput {
    /// Desired torso yaw delta this frame (radians).
    pub torso_yaw_delta: f32,
    /// Whether jump jets are firing this frame.
    pub jump_jets_active: bool,
    /// Heat generated by weapons this frame (0-1 scale).
    pub weapon_heat: f32,
}

/// Vehicle control system — handles enter/exit, mech features, vehicle movement.
pub struct VehicleSystem {
    /// Per-entity mech state, keyed by entity id bits.
    mech_states: HashMap<u64, MechState>,
}

impl VehicleSystem {
    pub fn new() -> Self {
        Self {
            mech_states: HashMap::new(),
        }
    }

    /// Get mech state for an entity (read-only).
    pub fn mech_state(&self, entity_bits: u64) -> Option<&MechState> {
        self.mech_states.get(&entity_bits)
    }

    /// Check whether a mech is overheated (weapons disabled).
    pub fn is_overheated(&self, entity_bits: u64) -> bool {
        self.mech_states
            .get(&entity_bits)
            .map_or(false, |s| s.overheated)
    }
}

impl System for VehicleSystem {
    fn name(&self) -> &str {
        "VehicleSystem"
    }

    fn tick(&mut self, world: &mut hecs::World, dt: f32, data: &DataStore) {
        // ── 1. Handle enter vehicle commands ────────────────────────
        if let Some(cmd) = data.get::<EnterVehicleCommand>("enter_vehicle") {
            self.handle_enter(world, cmd);
        }

        // ── 2. Handle exit vehicle commands ─────────────────────────
        if let Some(cmd) = data.get::<ExitVehicleCommand>("exit_vehicle") {
            self.handle_exit(world, cmd);
        }

        // ── 3. Update mech-specific state (heat, jump jets, torso) ──
        let mech_input = data.get::<MechInput>("mech_input").cloned().unwrap_or_default();
        self.tick_mechs(world, dt, &mech_input);
    }
}

impl VehicleSystem {
    /// Transfer `Controllable` from player to vehicle, seat the player.
    fn handle_enter(&mut self, world: &mut hecs::World, cmd: &EnterVehicleCommand) {
        let player = match hecs::Entity::from_bits(cmd.player_entity) {
            Some(e) => e,
            None => return,
        };
        let vehicle = match hecs::Entity::from_bits(cmd.vehicle_entity) {
            Some(e) => e,
            None => return,
        };

        // Verify player currently has Controllable
        if world.get::<&Controllable>(player).is_err() {
            return;
        }

        // Check vehicle has a free seat
        let seat_free = world
            .get::<&VehicleSeat>(vehicle)
            .map(|s| s.occupant_key.is_none())
            .unwrap_or(false);

        if !seat_free {
            return;
        }

        // Move Controllable: remove from player, add to vehicle
        let _ = world.remove_one::<Controllable>(player);
        let _ = world.insert_one(vehicle, Controllable);

        // Assign seat
        if let Ok(mut seat) = world.get::<&mut VehicleSeat>(vehicle) {
            seat.occupant_key = Some(cmd.player_key.clone());
        }

        // Initialize mech state if this vehicle doesn't have one yet
        self.mech_states
            .entry(cmd.vehicle_entity)
            .or_insert_with(MechState::default);
    }

    /// Transfer `Controllable` back to player, unseat, place player near vehicle.
    fn handle_exit(&mut self, world: &mut hecs::World, cmd: &ExitVehicleCommand) {
        let player = match hecs::Entity::from_bits(cmd.player_entity) {
            Some(e) => e,
            None => return,
        };

        // Find which vehicle this player occupies by scanning all VehicleSeats.
        // We need to collect first to avoid borrow conflicts.
        let occupied: Vec<(hecs::Entity, u64)> = world
            .query::<&VehicleSeat>()
            .iter()
            .filter(|(_, seat)| seat.occupant_key.is_some())
            .map(|(entity, _)| (entity, entity.to_bits().into()))
            .collect();

        let mut vehicle_entity = None;
        let mut vehicle_pos = Vec3::ZERO;

        for (entity, _bits) in &occupied {
            // Check if this vehicle has Controllable (meaning our player is driving it)
            if world.get::<&Controllable>(*entity).is_ok() {
                vehicle_entity = Some(*entity);
                if let Ok(tf) = world.get::<&Transform>(*entity) {
                    vehicle_pos = tf.position;
                }
                break;
            }
        }

        let vehicle = match vehicle_entity {
            Some(v) => v,
            None => return,
        };

        // Move Controllable back to player
        let _ = world.remove_one::<Controllable>(vehicle);
        let _ = world.insert_one(player, Controllable);

        // Clear seat
        if let Ok(mut seat) = world.get::<&mut VehicleSeat>(vehicle) {
            seat.occupant_key = None;
        }

        // Place player near vehicle
        if let Ok(mut tf) = world.get::<&mut Transform>(player) {
            tf.position = vehicle_pos + Vec3::new(EXIT_OFFSET, 0.0, 0.0);
        }

        // Stop vehicle movement
        if let Ok(mut vel) = world.get::<&mut Velocity>(vehicle) {
            vel.linear = Vec3::ZERO;
        }
    }

    /// Update all mech entities: heat dissipation, jump jets, torso twist.
    fn tick_mechs(&mut self, world: &mut hecs::World, dt: f32, input: &MechInput) {
        // Collect controlled vehicle entities (they have both Controllable and VehicleSeat)
        let controlled_vehicles: Vec<(hecs::Entity, u64)> = world
            .query::<(&Controllable, &VehicleSeat)>()
            .iter()
            .map(|(entity, _)| (entity, entity.to_bits().into()))
            .collect();

        for (_entity, bits) in &controlled_vehicles {
            let state = self.mech_states.entry(*bits).or_insert_with(MechState::default);

            // ── Heat management ─────────────────────────────────────
            // Add weapon heat
            state.heat = (state.heat + input.weapon_heat * dt).min(1.0);

            // Dissipate heat over time
            state.heat = (state.heat - HEAT_DISSIPATION_RATE * dt).max(0.0);

            // Overheat state transitions
            if !state.overheated && state.heat >= OVERHEAT_THRESHOLD {
                state.overheated = true;
                log::info!("Mech {:016x} overheated — weapons disabled", bits);
            } else if state.overheated && state.heat <= COOLDOWN_THRESHOLD {
                state.overheated = false;
                log::info!("Mech {:016x} cooled down — weapons re-enabled", bits);
            }

            // ── Torso twist ─────────────────────────────────────────
            state.torso_yaw = (state.torso_yaw + input.torso_yaw_delta)
                .clamp(-MAX_TORSO_YAW, MAX_TORSO_YAW);

            // ── Jump jets ───────────────────────────────────────────
            let entity = match hecs::Entity::from_bits(*bits) {
                Some(e) => e,
                None => continue,
            };

            if input.jump_jets_active && state.jump_jet_fuel > 0.0 {
                state.jump_jet_fuel = (state.jump_jet_fuel - JUMP_JET_FUEL_RATE * dt).max(0.0);

                if let Ok(mut vel) = world.get::<&mut Velocity>(entity) {
                    vel.linear.y += JUMP_JET_IMPULSE * dt;
                }
            }
        }
    }
}
